[project]
name = "supply-chain-verification"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.chain_verification-contract]
path = "contracts/chain_verification-contract.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
